language: cpp
compiler:
  - gcc
before_install:
  - 'ci/before_install.sh'
env:
  global:
  matrix:
    - BUILD_CORE_ONLY=OFF BUILD_TYPE=Debug
    - BUILD_CORE_ONLY=OFF BUILD_TYPE=Release
    - BUILD_CORE_ONLY=ON BUILD_TYPE=Debug
    - BUILD_CORE_ONLY=ON BUILD_TYPE=Release
before_script: cmake -DBUILD_CORE_ONLY=$BUILD_CORE_ONLY -DCMAKE_BUILD_TYPE=$BUILD_TYPE .
script:
  - make
  - sudo ldconfig --verbose # So the test executeables can detect libtinyxml2
  #- if [ $BUILD_CORE_ONLY = OFF ]; then make test; fi
after_failure:
  - cat Testing/Temporary/LastTest.log
  - cat Testing/Temporary/LastTestsFailed.log
